title: Jeffrey Stanaway, MPH PhD
#logo: /assets/img/headshot_circle.png
description: CV and portfolio
#show_downloads: false
#theme: jekyll-theme-minima
theme: minima
 # Generate social links in footer.
 # social_links:
 #  - { platform: github,         user_url: "https://github.com/jstanaway/jstanaway.github.io" }
 #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=URpg89oAAAAJ&hl=en" }
 #  - { platform: linkedin,       user_url: "hhttps://www.linkedin.com/in/jeffrey-stanaway-26496b86/" }
